import Head from "next/head";
import Header from "../../components/Header";
import LocationOnIcon from "@mui/icons-material/LocationOn";
import ImageContainer from "../../components/ImageContainer";
import { useState } from "react";
import Slider from "../../components/Slider";
export default function SingleHotel() {
  const images = [
    "/assets/property/resort.png",
    "/assets/property/boat.png",
    "/assets/property/cabins.png",
    "/assets/property/resort.png",
    "/assets/property/villas.png",
    "/assets/property/resort.png",
    "/assets/property/apartment.png",
    "/assets/property/villas.png",
  ];
  const [slideNumber, setSlideNumber] = useState(0);
  const [openSlider, setOpenSlider] = useState(false);

  return (
    <div>
         
      <Head>
        <title>Hotel Reservation | Hotel </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      { openSlider? <Slider slideNumber={slideNumber} images={images} setOpenSlider={setOpenSlider} setSlideNumber={setSlideNumber}/>:" "}
      <div className="p-2 flex mt-2 mx-5">
        <div className="w-full flex justify-between">
          <div className="w-[80%] flex flex-col space-y-1">
            <h1 className="text-xx font-semibold">Tower Street Apartments</h1>
            <div className="flex items-center justify-start">
              <LocationOnIcon className=" text-xs text-gray-500" />
              <p className="text-xs">
                {" "}
                5 Baztowa,old town, 33-332 krakow, poland
              </p>
            </div>

            <h1 className="text-xs">Excellent location -500m from center</h1>
            <h1 className="text-xs text-green-600">
              Book a stay over $144 at this property and get a free airport taxi
            </h1>
          </div>
          <div className="w-[20%] flex flex-col">
            <button className=" flex-start text-xs p-2 rounded-full transition duration-40 hover:bg-blue-600 bg-blue-800 text-white flex items-center justify-center cursor-pointer w-[75%]">
              Reserve or Book Now!!
            </button>
          </div>
        </div>
      </div>
      <ImageContainer images={images} setOpenSlider={setOpenSlider} setSlideNumber={setSlideNumber}/>

      <div className="mx-5 flex justify-between p-2">
<div className="p-1 flex flex-col w-[80%]">
<h1 className="text-2xl font-bold text-gray-500">Stay in the heart of krakow</h1>
<p className="text-xs">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Possimus, dolore voluptatum! Repellat est, aliquid aspernatur soluta doloremque reiciendis impedit odio, ut inventore possimus perspiciatis eos nostrum. Reprehenderit Lorem ipsum dolor sit amet, consectetur adipisicing elit. Possimus, dolore voluptatum! Repellat est, aliquid aspernatur soluta doloremque reiciendis impedit odio, ut inventore possimus perspiciatis eos nostrum. Reprehenderit illo reiciendis aliquid? illo reiciendis aliquid?</p>
</div>
<div className="p-2 flex flex-col w-[20%] bg-blue-200 rounded-xl space-y-2">
<h1 className="text-xx font-bold">Perfect for a 9-night stay!!</h1>
<p className="text-xs">Loacated in the real heart of krakow,this property has excellent location</p>
<h1 className="text-xl font-bold text-gray-500">$945<p className="text-xl inline font-medium">(9 nights)</p></h1>
<button className="text-xs p-2 rounded-full transition duration-40 hover:bg-blue-600 bg-blue-800 text-white flex items-center justify-center cursor-pointer w-[90%] md:w-[70%]">Reserve or book now!!</button>
</div>
      </div>
    </div>
  );
}
