import Head from "next/head";
import Image from "next/image";
import Navbar from "../components/Navbar";
import { motion } from "framer-motion";
import Header from "../components/Header";
import Featured from "../components/Featured";
export default function Home() {
  return (
    <motion.div animate={{opacity:1}} initial={{opacity:0}} transition={{duration:0.8}}>
      <Head>
        <title>Hotel Reservation</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <Header type="home"/>
    <div className="z-index-0 mt-5 flex flex-col gap-2 p-2 items-center">
<Featured/>
    </div>
    </motion.div>
  );
}
