import Head from "next/head";
import { motion } from "framer-motion";
import Header from "../components/Header";
import PropertyList from "../components/PropertyList";
import Featured from "../components/Featured";
import HomeGuest from "../components/HomeGuest";
import MailList from "../components/MailList";
import { AnimatePresence } from "framer-motion";
export default function Home() {
  return (
    <motion.div
      animate={{ opacity: 1 }}
      initial={{ opacity: 0 }}
      transition={{ duration: 0.8 }}
    >
      <Head>
        <title>Hotel Reservation | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header type="home" />
      <div className="z-index-0 mt-5 flex flex-col gap-2 p-2 items-center">
        <Featured />
      </div>
      <h1 className="font-bold text-xl text-left px-12 mt-2 text-gray-600">
        Browse by Property type
      </h1>
      <AnimatePresence>
        <PropertyList />
      </AnimatePresence>
      <h1 className="font-bold text-xl text-left px-12 mt-2 text-gray-600">
        Homes guests love
      </h1>
      <HomeGuest />
      <MailList />
    </motion.div>
  );
}
