import  Head  from "next/head";

export default function list() {
  return (
    <div>
         <Head>
        <title>Hotel Reservation | Lists</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  )
}
