import  Head  from "next/head";
import Header from "../components/Header";
import Navbar from "../components/Navbar";
export default function list() {
  return (
    <div>
         <Head>
        <title>Hotel Reservation | Lists</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
    </div>
  )
}
